# Generated by Django 3.0.1 on 2020-11-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200925_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sizing',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
